--- 
server: 
  port: 8090
spring: 
  application: 
    name: student
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    password: ~
    url: "jdbc:mysql://localhost:3306/student"
    username: root
  jpa: 
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
